// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbiqHCqoDpLjJXe2NmHTmJbjrUoX96uYw',
    appId: '1:836308904683:web:12f23cef842b2b74c22cae',
    messagingSenderId: '836308904683',
    projectId: 'tu-dormitory',
    authDomain: 'tu-dormitory.firebaseapp.com',
    storageBucket: 'tu-dormitory.firebasestorage.app',
    measurementId: 'G-58ZVNME9C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVSWy3-x-d53JJPhUPw_6cWC0cEuXWMFE',
    appId: '1:836308904683:android:e2b1095f8ac32886c22cae',
    messagingSenderId: '836308904683',
    projectId: 'tu-dormitory',
    storageBucket: 'tu-dormitory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI-bgU_B0gNhkHnHjYCZCx3HAFeiMsYIA',
    appId: '1:836308904683:ios:0051f701d1303aa8c22cae',
    messagingSenderId: '836308904683',
    projectId: 'tu-dormitory',
    storageBucket: 'tu-dormitory.firebasestorage.app',
    iosBundleId: 'com.example.tuDormitory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbiqHCqoDpLjJXe2NmHTmJbjrUoX96uYw',
    appId: '1:836308904683:web:7d69ea791a1ff26bc22cae',
    messagingSenderId: '836308904683',
    projectId: 'tu-dormitory',
    authDomain: 'tu-dormitory.firebaseapp.com',
    storageBucket: 'tu-dormitory.firebasestorage.app',
    measurementId: 'G-LFBSCRER86',
  );
}
